### ISSUE TITLE
Iterar para mostrar resultados

### ISSUE THREAD

**Issue by andresmgsl** [dasinb0/monorepo-Angular#2]
Luego de obtener los tokens (wallet/all_tokens) te falta iterar en el resultado para mostrarlo.

Si puedes arreglarlo, podriamos aprobar el Reto.

**Comment by dasinb0** [comment]
dale ahora lo reviso

**Comment by dasinb0** [comment]
fíjate ahí hice cambios, tengo que acomodar las ramas. Otra cosa es que todavía no tengo SILLY. 

https://github.com/dasinb0/monorepo-Angular/tree/master

**Comment by andresmgsl** [comment]
Reviso y te comento.. con respecto a los SILLY, te escribi al privado por discord para resolver más rápido.

**Comment by andresmgsl** [comment]
Ahora si, todo funciona! Muchas gracias!

**Comment by dasinb0** [comment]
sisi ahora sigo con el reto 3, gracias :D
