### ISSUE TITLE
Reto 3 - Comentarios

### ISSUE THREAD

**Issue by andresmgsl** [dasinb0/monorepo-Angular#3]
Muy buen día  Diego, espero estés muy bien... Ya he revisado el Reto 3 y has complido con los objetivos que se pedían, felicidades :grin: ... Lo que si, es que tienes un detalle que sería bueno acomodar:  para poder transferir el monto que muestras en tu modal de transferencia, tienes que multiplicar por el número de decimales que tiene el token, en este caso SILLY tiene 9, por lo que el amount correcto para transferir 1 SILLY, sería 1 * 10⁹ ... Actualmente pasas el amount directo con el valor que te viene del formulario, entonces al colocar 1 de amount, realmente estarías transfirendo 0,000000001 SILLY (la unidad mínima)... Hay muchas formas de arreglarlo, la mas sencilla es simplemente multiplicar el amount antes de hacer la llamada. Te dejo unas imágenes para intentar ilustrar un poco mejor lo que digo:

Sin multiplicar el amount, se ve así la transferencia (fíjate que dice 0 en el amount de SILLY del modal de la wallet) ->
![Screenshot from 2024-02-26 12-35-02](https://github.com/dasinb0/monorepo-Angular/assets/6069831/8209220a-29a2-4f58-9e06-1a71dbfaeddc)

Multiplicando el amount por los decimales se ve así (Fíjate como ahora si se muestra 1 SILLY )->
![Screenshot from 2024-02-26 12-37-31](https://github.com/dasinb0/monorepo-Angular/assets/6069831/f794f447-8ea7-4932-b8fd-d9c09c13df8d)

La linea de código es aquí ->
![Screenshot from 2024-02-26 12-36-54](https://github.com/dasinb0/monorepo-Angular/assets/6069831/77ee57ec-d2db-4d7d-b6ef-a6287e2ea1a0)

Si no logré explicarme correctamente, te pido por favor me avises!!

**Comment by dasinb0** [comment]
Ah genial lo corrijo, lo mejoro un toque mas visualmente y subo los cambios en el bono. Gracias 👍

**Comment by andresmgsl** [comment]
Perfectoo DIego, cualquier cosa ya sabes, estamos aquí 100% disponibles.

**Comment by dasinb0** [comment]
Tarde pero ya envié el bono del reto 3. Saludos.
